name: Build and Upload Jar

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission to script
      run: bash -c "chmod +x script.sh"

    - name: Install LocaleLib for Folia
      shell: bash
      run: |
       git clone https://github.com/Euphillya/LocaleLib-Folia
       cd LocaleLib-Folia
       mvn clean compile package
       mvn install:install-file \
         -Dfile="target/LocaleLib-4.1.2-Folia.jar" \
         -DgroupId="me.pikamug.localelib" \
         -DartifactId="LocaleLib" \
         -Dversion="4.1.2-Folia" \
         -Dpackaging="jar"
       cd ..

    - name: Update upstream and apply patches
      shell: bash
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Action Github"
        ./script.sh updateUpstream
        ./script.sh applyPatches

    - name: Build with Maven
      shell: bash
      run: |
        cd Quests-Patchs
        mvn clean compile install

    - name: Upload Jar file
      uses: actions/upload-artifact@v4
      with:
        name: compiled-jar
        path: Quests-Patchs/dist/target/*.jar
