name: Build and Upload Jar

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission to script (Linux)
      if: runner.os == 'Linux'
      run: chmod +x script.sh

    - name: Setup Git for Windows
      if: runner.os == 'Windows'
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        git config --global core.symlinks true
        git config --global core.editor "code --wait"

    - name: Install Git Bash (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: choco install git

    - name: Update upstream and apply patches
      shell: bash
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Action Github"
        ./script.sh updateUpstream
        ./script.sh applyPatches

    - name: Build with Maven
      shell: bash
      run: |
        cd Quests-Patch
        mvn clean compile install

    - name: Upload Jar file
      uses: actions/upload-artifact@v3
      with:
        name: compiled-jar
        path: Quests-Patch/dist/target/*.jar
